### ISSUE TITLE
darwin

### ISSUE THREAD

**Issue by gedw99** [Inkeliz/gowebview#1]
i know darwin is not supported. not needing CGO is a great idea.

It is probably only a matter of looking into the right system calls.

but here is the error 

```

go build -o ./example .
# github.com/inkeliz/gowebview
Undefined symbols for architecture x86_64:
  "_webview_create", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_create in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_create)
  "_webview_destroy", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_destroy in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_destroy)
  "_webview_eval", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_eval in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_eval)
  "_webview_get_window", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_get_window in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_get_window)
  "_webview_init", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_init in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_init)
  "_webview_navigate", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_navigate in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_navigate)
  "_webview_run", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_run in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_run)
  "_webview_set_size", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_set_size in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_set_size)
  "_webview_set_title", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_set_title in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_set_title)
  "_webview_terminate", referenced from:
      __cgo_fb6f7ea8c7eb_Cfunc_webview_terminate in _x002.o
     (maybe you meant: __cgo_fb6f7ea8c7eb_Cfunc_webview_terminate)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build] Error 2
```

**Comment by gedw99** [comment]
Ok i get how the archi works
https://github.com/Inkeliz/gowebview/blob/master/generator/generate.go

is this a comöiled version of https://github.com/webview/webview that is embedded ?

**Comment by Inkeliz** [comment]
Well, for Darwin/Linux it still needs CGO (and the .dylib/.so must be in the same folder): just as the regular `webview/webview`. It's a slightly modified version of https://github.com/webview/webview. I adapt to conform to the new `WebView` interface. 

------------

The `generator.go` creates the `lib_*.go` files (such as https://github.com/Inkeliz/gowebview/blob/master/lib_window.go). All those files (only used by Windows at `webview_windows.go`) are extracted when you run the `New()` function:

https://github.com/Inkeliz/gowebview/blob/3d75c1d755e6170a77458ac1c44904f5aac3c3ba/webview_windows.go#L41-L49

That makes it possible to load the DLL. The DDL is loaded after the execution, using `LazyLoad`:

https://github.com/Inkeliz/gowebview/blob/3d75c1d755e6170a77458ac1c44904f5aac3c3ba/webview_windows.go#L57-L60

That is the trick to avoid CGO and to make possible to extract the DLL.

It's not possible to do that on the `webview/webview`, since Golang looks for the DLL at the startup of the software, [so you can't execute anything because it crashes](https://github.com/webview/webview/issues/366#issuecomment-669479989). That was the only reason to create that new library.

That changes is only applied to Windows, others plataforms remains unchanged.

---------

About the lib folder, it has all `.dll`/`.dylib`/`.so`, and you can get from https://github.com/webview/webview_csharp/tree/master/libs. It's only used by `go generate` to create `lib_*.go` files.

In that case, copy the [`libwebview.dylib` ](https://github.com/webview/webview_csharp/tree/master/libs) and paste that file in the same folder of the executable. It may works since it's the same of `webview/webview` (it uses CGO).

---------

Android is my priority for now. Of course, it will use CGO (since it's using JNI), but it's what I need for now. I may remove the Darwin/Linux stuff altogether or change to make it work with CGO, and I don't know. For now, I'm ignoring Darwin/Linux. :\

**Comment by gedw99** [comment]
Ok thanks for explaining the hooks. 
I like the design a lot. CGO is a pain for packaging aspects.

I would like to help make this work on Darwin and Linux without CGO because an org I am involved with a project that needs it. The need is so we can have flutter web views and I can add it to this as a plug-in to this project : https://github.com/go-flutter-desktop/plugins so other can also have it. Making it work as a web view for flutter desktop is minimal complexity btw.

The open source org project: https://github.com/getcouragenow/main
It’s using flutter and golang.

It will be used to play videos on desktop, do video conferencing and single sign on Dialoge.

I think I can get it done but it might be a PITA for you if you do not want the attention. I am fine with forking your project and merging your windows and android stuff into the fork. Just tell me know what works for you.

**Comment by Inkeliz** [comment]
I think forking will be the best solution. (:

I finally get the Android version to work, at least the basic stuff (loading pages, almost). However, `gomobile build` nor `go build` works, since it needs some Java to be glued together. However, to abstract all java stuff: I'm creating one executable that runs as `gowebview build` (instead of `go build`), so you get the `.apk` quickly.
