### ISSUE TITLE
debian run go webview ─# go get -u "github.com/inkeliz/gowebview" # github.com/inkeliz/gowebview ../github.com/inkeliz/gowebview/gowebview.go:88:9: undefined: newWindow

### ISSUE THREAD

**Issue by passerbyo** [Inkeliz/gowebview#22]
─# go get -u "github.com/inkeliz/gowebview"
# github.com/inkeliz/gowebview
../github.com/inkeliz/gowebview/gowebview.go:88:9: undefined: newWindow

**Comment by DAT4** [comment]
The reason you get this error is because you are running another OS than windows or android. If you check the source code the function newWindow is only implemented for windows and android - and I don't know if the maintainer is planning on implementing it for other platforms.

**Comment by inkeliz** [comment]
Yes, that package only supports Windows/Android. If you need Linux support, take a look at https://github.com/webview/webview, as mentioned on README.

I made another package which works on iOS/macOS/Android/Windows and JS: https://github.com/inkeliz/giowebview (and also https://github.com/gioui-plugins/gio-plugins/tree/main/webviewer). That new version was primary designed to work with GioUI, so it's possible to embed the webview instead of open one new window. That also provides more features (such as read cookies, execute JS code...). However, that **don't** support Linux/FreeBSD, _because I don't care about linux_.
